In [6]:
import numpy as np 
import pandas as pd
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

import pickle


In [7]:
data_dir = '/home/simon/Documents/Bodies/data/OD_dataframes_compiled/'

with open(f'{data_dir}df_od_full.pkl', 'rb') as file:
    df_full = pickle.load(file)

fix_dict = {'Habur border crossing' : 'Habur Port', 'Basra Basra' : 'Basra', 'Basrah' : 'Basra', 'Baghdad05' : 'Baghdad','Arab jabour' : 'Baghdad',
            'Arab Jabour': 'Baghdad', 'Hay al Waahda' : 'Bagdad', 'Taqqadum' : 'Al Taqaddum', 'Ouwja' : 'Al-Awja', 'Husayba' : 'Husaybah', 
            "no-man's land": 'Al Karamah Border Crossing', 'Zacho' : 'Zaxo'}

df_full.replace(fix_dict, inplace= True)
cities = df_full['city'].unique()[1:]#You do not take nan

In [30]:
latitude = []
longitude = []
geo_countries = []

latitude_irq = []
longitude_irq = []
geo_countries_irq = []

for i in cities: 
    geolocator = Nominatim(user_agent='spm@ifs.ku.dk')
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
    
    try: # the idea here is to catch both timeout and non-returns
        location = geocode(i)

        latitude.append(location.latitude)
        longitude.append(location.longitude)
        geo_countries.append(location.address.split(',')[-1])
    
    except:

        latitude.append(None)
        longitude.append(None)
        geo_countries.append(None)

    try:

        location_irq = geocode(f'{i}, Iraq')

        latitude_irq.append(location_irq.latitude)
        longitude_irq.append(location_irq.longitude)
        geo_countries_irq.append(location_irq.address.split(',')[-1])

    except:

        latitude_irq.append(None)
        longitude_irq.append(None)
        geo_countries_irq.append(None)

df_cities = pd.DataFrame({'city' : cities, 'latitude' : latitude, 'longitude' : longitude, 'geo_country': geo_countries, 
                          'latitude_irq' : latitude_irq, 'longitude_irq' : longitude_irq, 'geo_country_irq': geo_countries_irq })

In [31]:
df_cities


city   latitude  longitude             geo_country  \
0                      Baghdad  33.302431  44.378799                  العراق   
1                        Basra  30.495237  47.809098                  العراق   
2                     Husaybah  33.420684  43.453298                  العراق   
3                       Baquba  33.743727  44.649523                  العراق   
4                    Karabilah  34.390889  41.046437                  العراق   
5                        Mosul  36.343694  43.099716                  العراق   
6                      Ad Dawr  34.458349  43.795799                  العراق   
7                        Hilla  32.482245  44.432813                  العراق   
8                      Samarra  34.200000  43.900000                  العراق   
9                       Dujail  33.837069  44.247461                  العراق   
10                    Ar Rabit  34.427567  41.037860                  العراق   
11                      Bagdad  33.302431  44.378799                  العراق   
12                    Fallujah  33.353214  43.787567                  العراق   
13                  Habbaniyah  33.278889  43.688611                  العراق   
14                 Al Taqaddum  33.332207  43.600520                  العراق   
15                     Kerbala  32.451170  43.819662                  العراق   
16                     Al-Awja  31.949040  35.465486   Palestinian Territory   
17                  Abu Ghraib  33.304525  44.146337                  العراق   
18                      Kirkuk  35.470342  44.395723                  العراق   
19                     Al Qaim  36.508797  43.184534                  العراق   
20                        Taji  33.529892  44.277464                  العراق   
21                       Rawah  35.081981  43.101652                  العراق   
22                       Balad  34.001313  44.152789                  العراق   
23  Al Karamah Border Crossing  32.726500  38.979640                  الأردن   
24                     Baqouba  33.743727  44.649523                  العراق   
25                      Ramadi  33.425986  43.299922                  العراق   
26                   Al-Samawa  24.608853  46.844328                السعودية   
27                    Kara-Ula  31.596787  35.028491   Palestinian Territory   
28                        Zaxo  37.154300  42.700787                  العراق   
29                     Al Asad  36.079277  38.069992                   سوريا   
30                       Najaf  32.001023  44.329993                  العراق   
31                       Cizre  37.327481  42.189461                 Türkiye   
32                      Sirnak  37.521958  42.457031                 Türkiye   
33                     Falluja  33.353214  43.787567                  العراق   
34                       cizre  37.327481  42.189461                 Türkiye   
35                  Habur Port  37.149920  42.568510                 Türkiye   
36                   Manhattan  40.789624 -73.959894           United States   

    latitude_irq  longitude_irq geo_country_irq  
0      33.302431      44.378799          العراق  
1      30.495237      47.809098          العراق  
2      33.420684      43.453298          العراق  
3      33.743727      44.649523          العراق  
4      34.390889      41.046437          العراق  
5      36.343694      43.099716          العراق  
6      34.458349      43.795799          العراق  
7      32.482245      44.432813          العراق  
8      34.200000      43.900000          العراق  
9      33.837069      44.247461          العراق  
10     34.427567      41.037860          العراق  
11     33.302431      44.378799          العراق  
12     33.353214      43.787567          العراق  
13     33.278889      43.688611          العراق  
14     33.332207      43.600520          العراق  
15     32.451170      43.819662          العراق  
16     34.533333      43.733333          العراق  
17     33.304525      44.146337          العراق  
18     35.470342      44.395723    

In [41]:
df_cities.iloc[1]['city']

'Basra'

In [46]:
for i in range(0, df_cities.shape[0]):

    if df_cities.iloc[i]['latitude'] != df_cities.iloc[i]['latitude_irq'] or df_cities.iloc[i]['longitude'] != df_cities.iloc[i]['longitude_irq']:
        print(f'{df_cities.iloc[i]['city']} {df_cities.iloc[i]['geo_country']}')
        print()
        print('\n')


Al-Awja
 Palestinian Territory


Al Karamah Border Crossing
 الأردن


Al-Samawa
 السعودية


Kara-Ula
 Palestinian Territory


Al Asad
 سوريا


Cizre
 Türkiye


Sirnak
 Türkiye


cizre
 Türkiye


Habur Port
 Türkiye


Manhattan
 United States




In [12]:
location

Location(Manhattan, New York County, New York, United States, (40.7896239, -73.9598939, 0.0))

In [81]:
for key in fix_dict.keys():
    print(fix_dict[key])

Habur Port
Basra
Baghdad


In [ ]:
df = df.replace(d)

In [ ]:
df.loc[df.infants == 'n', 'infants'] = 0

In [ ]:
df.loc[df[col] == 'n', col] = 0

In [86]:
df_full[df_full['city'] == key ,'city']

TypeError: '(0         False
1         False
2         False
3         False
4         False
          ...  
152430    False
152431    False
152432    False
152433    False
152434    False
Name: city, Length: 152435, dtype: bool, 'city')' is an invalid key

In [83]:
for key in fix_dict.keys():
    df_full[df_full.loc[:,'city'] == key].loc[:,'city'] = fix_dict[key]

/home/simon/anaconda3/envs/geopy_env/lib/python3.8/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [ ]:
cities = df_full['city'].unique()[1:]#You do not take nan

latitude = []
longitude = []
geo_city = []

latitude_irq = []
longitude_irq = []
geo_city_irq = []

for i in cities: 
    geolocator = Nominatim(user_agent='spm@ifs.ku.dk')
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
    
    location = geocode(i)
    location_irq = geocode(f'{i}, Iraq')

    latitude.append(location.latitude)
    longitude.append(location.longitude)
    geo_city.append(location.address.split(' ')[-1])
    
    latitude_irq.append(location_irq.latitude)
    longitude_irq.append(location_irq.longitude)
    geo_city_irq.append(location_irq.address.split(' ')[-1])

In [58]:
df_full.loc[:,'city'].unique()

array([nan, 'Baghdad', 'Basra', 'Husaybah', 'Baquba', 'Karabilah',
       'Mosul', 'Ad Dawr', 'Hilla', 'Samarra', 'Dujail', 'Ar Rabit',
       'Hay al Waahda', 'Fallujah', 'Habbaniyah', 'Taqqadum', 'Kerbala',
       'Ouwja', 'Abu Ghraib', 'Kirkuk', 'Al Qaim', 'Basrah', 'Taji',
       'Rawah', 'Balad', "no-man's land", 'Baqouba', 'Ramadi',
       'Al-Samawa', 'Arab Jabour', 'Kara-Ula', 'Zacho', 'Husayba',
       'Al Asad', 'Najaf', 'Basra Basra', 'Arab jabour', 'Cizre',
       'Sirnak', 'Falluja', 'cizre', 'Baghdad05', 'Habur border crossing',
       'Manhattan'], dtype=object)

In [57]:
df_full.loc[:,'object name'].unique()

array([nan, 'Baghdad truck bomb', 'Civilian09', 'Karabilah02',
       'SteelCurtain26', 'suicidebomb', 'Baghdad Cinema', 'Mosul',
       'PoliceBomb02', 'Saddams last hiding place', 'Pension payment',
       'Samarra', 'Chen', 'ArRabit19', 'KarabilahRaids10', 'Refugees04',
       'Clusterbomb victim', 'Mosul24', 'PalestineHotel', 'Traffic',
       'Ramadan02', ' Saddam City', 'Refugees02', 'Executed prisoners',
       'SaddamTrial03', 'ArabLeague03', 'IPDemonstration',
       'Statue workshop', 'ArRabit25', 'IraqChristians17', 'MOI02',
       'DanceCompany08', 'BayiaaBomb', 'Ramana26', 'Basra06',
       'Civilian11', 'JointSecuritySite', 'Financeminister',
       'Karabilah10', 'BaghdadCollege21', 'trash06', 'NYTimesCompound11',
       'SaddamTrial06', 'Karabilah01', 'Rawah', 'Mosul42', 'Mahdi07',
       'BaghdadCollege10', 'Ramadan01', 'Financeminister02',
       'GoldenMosque', 'Karabilah17', 'Spear04', 'Rawah08', 'Karabilah16',
       'Refugees07', 'trash02', 'NYTimesCompound', 'Uba

In [ ]:
#fix


person_mean  person_median  person_fasterR50  person_fasterR101  \
94255          5.8            6.0                 6                  5   
98038          5.8            6.0                 6                  5   

       person_fasterX101  person_retinaR50  person_retinaR101  child_mean  \
94255                  6                 6                  6         1.5   
98038                  6                 6                  6         1.5   

       child_median  child_retinaR50  ...  org img name  date created  \
94255           1.5                1  ...  DSC_5991.jpg      20060919   
98038           1.5                1  ...  DSC_5991.jpg      20060919   

       time created       city  province/state  sub-location  \
94255   111447+0300  Baghdad05             NaN           NaN   
98038   111447+0300  Baghdad05             NaN           NaN   

                                   headline  by-line title  \
94255  Car bomb victims at Yarmouk Hospital            NaN   
98038  Car bomb victims at Yarmouk Hospital            NaN   

                                        caption/abstract  object name  
94255                                 Victims of a ca...       Yarmuk  
98038                                 Victims of a ca...       Yarmuk  

[2 rows x 101 columns]

In [40]:
test_cities = df_full['city'].unique()


In [33]:
test_cities = df_full['city'].unique()
geo_list = []
geo_list_irq = []

for i in test_cities[1:]: #You do not take nan
    geolocator = Nominatim(user_agent='spm@ifs.ku.dk')
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
    geo_list.append(geocode(i))
    geo_list_irq.append(geocode(f'{i}, Iraq'))

In [59]:
geocode('Samarra')

Location(سامراء, ناحية مرکز قضاء سامراء, قضاء سامراء, محافظة صلاح الدين, 34010, العراق, (34.2, 43.9, 0.0))

In [65]:
'العراق' == geo_list[1][0].split(' ')[-1]

True

In [61]:
geocode('Bagdad')

Location(بغداد, ناحية مرکز قضاء الکرخ, قضاء الکرخ, محافظة بغداد, العراق, (33.3024309, 44.3787992, 0.0))

In [63]:
geo_list[1][0].split(' ')[-1]

'العراق'

In [66]:
geo_list[1][1]

(33.3024309, 44.3787992)

In [71]:
geo_list[1].address.split(' ')[-1]
geo_list[1].latitude 
geo_list[1].longitude

'العراق'

In [67]:
test_cities = df_full['city'].unique()[1:]#You do not take nan

latitude = []
longitude = []
geo_city = []

latitude_irq = []
longitude_irq = []
geo_city_irq = []

for i in test_cities: 
    geolocator = Nominatim(user_agent='spm@ifs.ku.dk')
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
    
    location = geocode(i)
    location_irq = geocode(f'{i}, Iraq')

    latitude.append(location.latitude)
    longitude.append(location.longitude)
    geo_city.append(location.address.split(' ')[-1])
    
    latitude_irq.append(location_irq.latitude)
    longitude_irq.append(location_irq.longitude)
    geo_city_irq.append(location_irq.address.split(' ')[-1])

33.3024309

In [41]:
test_cities

array([nan, 'Baghdad', 'Basra', 'Husaybah', 'Baquba', 'Karabilah',
       'Mosul', 'Ad Dawr', 'Hilla', 'Samarra', 'Dujail', 'Ar Rabit',
       'Hay al Waahda', 'Fallujah', 'Habbaniyah', 'Taqqadum', 'Kerbala',
       'Ouwja', 'Abu Ghraib', 'Kirkuk', 'Al Qaim', 'Basrah', 'Taji',
       'Rawah', 'Balad', "no-man's land", 'Baqouba', 'Ramadi',
       'Al-Samawa', 'Arab Jabour', 'Kara-Ula', 'Zacho', 'Husayba',
       'Al Asad', 'Najaf', 'Basra Basra', 'Arab jabour', 'Cizre',
       'Sirnak', 'Falluja', 'cizre', 'Baghdad05', 'Habur border crossing',
       'Manhattan'], dtype=object)

In [8]:

geolocator = Nominatim(user_agent='spm@ifs.ku.dk')
location = geolocator.geocode("175 5th Avenue NYC")
print(location.address)
print((location.latitude, location.longitude))

Flatiron Building, 175, 5th Avenue, Manhattan Community Board 5, New York County, New York, 10010, United States
(40.741059199999995, -73.98964162240998)


In [9]:
geopy.RateLimiter

AttributeError: module 'geopy' has no attribute 'RateLimiter'


when you create the Nominatim object, just give it your email as an argument. nominatim_service = Nominatim(user_agent='my_email@myserver.com') and then call the service on whatever your input data is geolocator = RateLimiter(nominatim_service.geocode, min_delay_seconds=1) collisions['geocodes'] = collisions['location_string'].apply(geolocator)