In [2]:
#Per default, this is done in the prediction script. But this might be used to change the threshold after training to avoid retraining.

import numpy as np

from detectron2.engine import DefaultPredictor
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
from detectron2.data import MetadataCatalog, DatasetCatalog

import os
import pickle
# from utils import *

from collections import Counter
# import pandas as pd

from xml.etree import ElementTree, ElementInclude


In [3]:
model_name = 'retinanet_R_101_FPN_3x'
threshold = 0.3

In [4]:
def get_classes(img_dir):
    """Creates a list of classes and corrosponding ints. also a dict to translate"""

    obj_name = []

    # Get all objects that have been annotated
    for filename in os.listdir(img_dir):
        if filename.split('.')[1] == 'xml':
            box_path = os.path.join(img_dir, filename)

            tree = ElementTree.parse(box_path)
            lst_obj = tree.findall('object')

            for j in lst_obj:
                obj_name.append(j.find('name').text)
    
    classes = list(sorted(set(obj_name))) # all labesl
    classes_int = list(np.arange(0,len(classes))) # corrospoding int
    class_to_int = dict(zip(classes,classes_int)) # a dict to translate between them

    return(classes, classes_int, class_to_int)

def get_img_path(img_dir):

    """Creates a list of all image paths."""

    # right now this does not take into account whether the image was anotated or not.
    # It also does not handle test or train.

    img_path_list = []

    for root, dirs, files in os.walk(img_dir):
        for img_name in files:
            if img_name.split('.')[1] == 'jpg':
                img_path = os.path.join(img_dir, img_name)                
                img_path_list.append(img_path)

    return(img_path_list)

def get_int_to_class():
    # This is always the annotatedd folder..
    #annotated_img_dir = '/home/projects/ku_00017/data/raw/bodies/OD_images_annotated'  
    annotated_img_dir = '/home/simon/Documents/Bodies/data/jeppe/images'
    classes, classes_int, class_to_int = get_classes(annotated_img_dir)
    int_to_class = dict(zip(classes_int, classes))

    return int_to_class


def get_output_tX(model_name, threshold):

    # Get the instances_list
    #instances_list_dir = f'/home/projects/ku_00017/data/generated/bodies/detectron_outputs/{model}/instances_list.pkl'
    instances_list_dir = f'/home/simon/Documents/Bodies/data/computerome_outputs/detectron_outputs_test/{model_name}/instances_list.pkl'

    with open(instances_list_dir, 'rb') as file:
        instances_list = pickle.load(file)

    #img_dir = '/home/projects/ku_00017/data/raw/bodies/images_spanner' #full run!!!
    img_dir = '/home/simon/Documents/Bodies/data/jeppe/images'

    # get images path and int to class dict.
    img_path_list = get_img_path(img_dir)
    int_to_class = get_int_to_class()

    # containers:
    output_list = []
    all_img_feature_list = [] # to create the slim df, its easier this way...

    # number of images to predict
    total_count = len(img_path_list)


    total_count = 10
    # prediction loop
    for count, img_path in enumerate(img_path_list[0:total_count]):

        instance = instances_list[count]

        img_id = img_path.split('/')[-1].split('.')[0]

        img_dict = {'img_id': img_id, 'scores': None , 'pred_classes': None}

        mask = instance.scores.numpy()>threshold # maybe these scores should be used for more stuff.. lot of information here
    
        # only save instances above the threshold
        img_dict['scores'] = instance.scores.numpy()[mask]
        img_dict['pred_classes'] = instance.pred_classes.numpy()[mask]

        img_feature_Int_count = dict(Counter(instance.pred_classes.numpy()[mask])) # counting the classes - int encoded
        img_dict = {**img_dict, **img_feature_Int_count} # merging counts with other info 
        
        img_feature_list = [int_to_class[i] for i in instance.pred_classes.numpy()[mask]] # convert from int encoded feature to str of feature name
        img_feature_count = dict(Counter(img_feature_list)) # count the actual feature name
        img_dict = {**img_dict, **img_feature_count} # merging counts name with other info - actual feature

        output_list.append(img_dict)
        all_img_feature_list += img_feature_list #this will just be a list of all encountered features..

        print(f'img id: {img_id}, {count} of {total_count} done...', end = '\r')  

    # get the unique set of features - nice for the thin df.
    all_img_feature_list = list(set(all_img_feature_list))    

    return output_list, all_img_feature_list

In [4]:
# Get the instances_list
#instances_list_dir = f'/home/projects/ku_00017/data/generated/bodies/detectron_outputs/{model}/instances_list.pkl'
instances_list_dir = f'/home/simon/Documents/Bodies/data/computerome_outputs/detectron_outputs_test/{model_name}/instances_list.pkl'

with open(instances_list_dir, 'rb') as file:
    instances_list = pickle.load(file)

#img_dir = '/home/projects/ku_00017/data/raw/bodies/images_spanner' #full run!!!
img_dir = '/home/simon/Documents/Bodies/data/jeppe/images'

# get images path and int to class dict.
img_path_list = get_img_path(img_dir)
int_to_class = get_int_to_class()

# containers:
output_list = []
all_img_feature_list = [] # to create the slim df, its easier this way...

# number of images to predict
total_count = len(img_path_list)


total_count = 10

In [ ]:
img_dir = '/home/simon/Documents/Bodies/data/jeppe/images'

img_path_list = get_img_path(img_dir)


In [17]:
obj_path = img_path_list[0].split('.')[0] + '.xml'
#obj_path
obj_path.split('.')[0].split('/')[-1]

'JS49244'

In [6]:

# prediction loop
for count, img_path in enumerate(img_path_list[0:1]):

    instance = instances_list[count]

    img_id = img_path.split('/')[-1].split('.')[0]

    img_dict = {'img_id': img_id, 'scores': None , 'pred_classes': None}

    mask = instance.scores.numpy()>threshold # maybe these scores should be used for more stuff.. lot of information here

    # only save instances above the threshold
    img_dict['scores'] = instance.scores.numpy()[mask]
    img_dict['pred_classes'] = instance.pred_classes.numpy()[mask]

    img_feature_Int_count = dict(Counter(instance.pred_classes.numpy()[mask])) # counting the classes - int encoded
    img_dict = {**img_dict, **img_feature_Int_count} # merging counts with other info 
    
    img_feature_list = [int_to_class[i] for i in instance.pred_classes.numpy()[mask]] # convert from int encoded feature to str of feature name
    img_feature_count = dict(Counter(img_feature_list)) # count the actual feature name
    img_dict = {**img_dict, **img_feature_count} # merging counts name with other info - actual feature

    output_list.append(img_dict)
    all_img_feature_list += img_feature_list #this will just be a list of all encountered features..

    print(f'img id: {img_id}, {count} of {total_count} done...', end = '\r')  

# get the unique set of features - nice for the thin df.
all_img_feature_list = list(set(all_img_feature_list))    


In [18]:
model_name = 'faster_rcnn_R_50_FPN_3x'

instances_list_dir = f'/home/simon/Documents/Bodies/data/computerome_outputs/detectron_outputs/{model_name}/instances_list.pkl'
output_test1_dir = f'/home/simon/Documents/Bodies/data/computerome_outputs/detectron_outputs_test/{model_name}/output_list.pkl'

with open(instances_list_dir, 'rb') as file:
    instances_test1 = pickle.load(file)

with open(output_test1_dir, 'rb') as file:
    output_test1 = pickle.load(file)

In [22]:
len(instances_test1)

4999

In [23]:
len(output_test1)

4999

In [35]:
output_test1[0]['img_id']

'JS151934'

In [33]:

n_img = len(output_test1)

for i in range(n_img):

    # print(output_test1[i]['scores'])
    # print(instances_test1[i].scores.numpy())

    state = output_test1[i]['scores'] == instances_test1[i].scores.numpy()
    print(state)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True]
[]
[ True 

In [14]:
instance

Instances(num_instances=100, image_height=2912, image_width=4368, fields=[pred_boxes: Boxes(tensor([[1813.7258, 1770.7440, 2705.7173, 2832.1370],
        [3013.2534,  228.9782, 3434.5918,  746.2919],
        [3013.2534,  228.9782, 3434.5918,  746.2919],
        [1797.0717, 1729.3468, 2753.0044, 2846.1436],
        [2683.1272,   97.5336, 3091.0178,  609.4045],
        [2682.2107,   97.4008, 3082.8040,  595.8495],
        [3603.6387,  470.9247, 4368.0000, 1731.2805],
        [3612.0249,  460.1194, 4368.0000, 1702.2899],
        [1763.0414, 1743.7618, 2790.1060, 2842.4749],
        [3013.2534,  228.9782, 3434.5918,  746.2919],
        [2682.2107,   97.4008, 3082.8040,  595.8495],
        [2888.7288,  552.7346, 3787.3491, 1737.0278],
        [2142.1191, 1369.0505, 2911.3540, 1869.1936],
        [1797.0717, 1729.3468, 2753.0044, 2846.1436],
        [2339.4219,  256.9820, 2724.7390,  782.1522],
        [2138.7673, 1375.3075, 2908.0332, 1866.4442],
        [1797.0717, 1729.3468, 2753.0044, 28

In [9]:
instance.scores.numpy()[mask]

array([0.50052226, 0.4508566 , 0.43484658, 0.43036255, 0.41763982,
       0.39558092, 0.36777848, 0.3322071 , 0.33150813, 0.30872577,
       0.30692798, 0.30615625, 0.30315793, 0.302766  ], dtype=float32)

In [11]:
instance.pred_classes.numpy()[mask]

array([13, 13, 11, 11, 13, 11, 13, 11,  0,  0,  0, 13, 13,  5])

In [13]:
dict(Counter(instance.pred_classes.numpy()[mask]))

{13: 6, 11: 4, 0: 3, 5: 1}

In [7]:
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
output_list, all_img_feature_list = get_output_tX(model_name, threshold)

# pickle configurations and save
location = f'/home/projects/ku_00017/data/generated/bodies/detectron_outputs/{model_name}'
os.makedirs(location, exist_ok = True)

with open(location + f'/output_list_t{int(threshold*100)}.pkl', 'wb') as file:
    pickle.dump(output_list, file)

with open(location + f'/all_img_feature_list_t{int(threshold*100)}.pkl', 'wb') as file:
    pickle.dump(all_img_feature_list, file)